### ISSUE TITLE
add integration test with test song only added to test target for test purposes

### ISSUE THREAD

**Issue by chrisgonzgonz** [learn-co-curriculum/jukebox-views#1]

**Comment by AnnJohn** [comment]
@jmburges @markedwardmurray I'd like to close this or at least "Icebox" it for a later day - is this lab still being used, if so, is it okay in it's current form until we can assign it to be fixed?

**Comment by AnnJohn** [comment]
Iceboxing the issue

**Comment by markedwardmurray** [comment]
I don't even know what this issue is trying to describe, but I've probably addressed it in the rewrite that's pending review.

https://github.com/learn-co-curriculum/jukebox-views/pull/4
